version: '3.8'

services:
  backend:
    container_name: backend
    build: "./srcs/backend"
    networks:
      - my_network
    ports:
      - "800:443"
    volumes:
      - ./srcs/backend:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    container_name: frontend
    build: ./srcs/frontend
    networks:
      - my_network
    ports:
      - "3000:443"
    volumes:
      - ./srcs/frontend:/app
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    depends_on:
      - backend
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: cbolatdb
      POSTGRES_USER: cbolat
      POSTGRES_PASSWORD: 1111
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:

networks:
  my_network:
    name: my_network
    driver: bridge
    